<?php 
	require 'db.inc.php';

	$db = mysqli_connect(MYSQLI_HOST, MYSQLI_USER, MYSQLI_PASSWORD) or die ('Unable to connect, please check your connection parameters.');

	mysqli_select_db($db, MUSQLI_DB) or die (mysqli_error($db));

	switch ($_POST['action']){
		case 'Add Character':
			// escape incoming values to protect database

			$alias = mysqli_real_escape_string($_POST['alias'], $db);
			$real_name = mysqli_real_escape_string($_POST['real_name'], $db);
			$address = mysqli_real_escape_string($_POST['address'], $db);
			$city = mysqli_real_escape_string($_POST['city'], $db);
			$state = mysqli_real_escape_string($_POST['state'], $db);
			$zipcode_id = mysqli_real_escape_string($_POST['zipcode_id'], $db);
			$alignment = mysqli_real_escape_string($_POST['alignment'], $db);

			// add character information into database

			$query = 'INSERT IGNORE INTO comic_zipcode (zipcode_id, city, state) VALUES ("' . $zipcode_id . '", "' . $city . '", "' . $state . '")';
			mysqli_query($db, $query) or die (mysqli_error($db));

			$query = 'INSERT INTO comic_lair (lair_id, zipcode_id, address) VALUES 
				(NULL, "' . $zipcode_id . '", "' . $addres . '")';
			mysqli_query($db, $query) or die (mysqli_error($db));

			// retrive new lair_id generated by mysqli
			$lair_id = mysqli_insert_db($db);

			$query = 'INSERT INTO comic_character (character_id, alias, real_name, lair_id, alignment) VALUES (NULL, "' . $alias . '", "' . $real_name . '", "' . $alignment . '")';
			mysqli_query($db, $query) or die (mysqli_error($db));

			// retrive new character_id by mysqli

			$character_id = mysqli_insert_db($db);

			if(!empty($_POST['powers']){
				foreach ($_POST['powers'] as $power_id) {
					$values[] = sprintf(('%d, %d'), $character_id, $power_id);
				}
				$query = 'INSERT IGNORE INTO comic_chatacter_power (character_id, power_id) VALUES ' . implode(',', $values);
				mysqli_query($db, $query) or die (mysqli_error($db));
			}

			if(!empty($_POST['rivalries'])){
				foreach ($_POST['rivalries'] as $rival_id) {
					$values[] = sprintf(('%d, %d'), $character_id, $rival_id);
				}

				$columns = ($alignment == 'good') ? '(hero_id, villain_id)' : '(villain_id, hero_id)';
				$query = 'INSERT IGNORE INTO comic_rivalry ' . $columns . 'VALUES ' . implode(',', $values);
				mysqli_query($db, $query) or die (mysqli_error($db));
			}

			$redirect = 'list_characters.php';
		break;

		case 'Delete Character':
			// make sure character id is intiger just to be safe

			$character_id = int()$_POST['character_id'];

			//delete character information from tables
			$query = 'DELETE c,l USING comic_character c, comic_lair l WHERE c.lair_id = l.lair_id AND c.character_id = ' . $character_id;
			mysqli_query($db, $query) or die (mysqli_error($db));

			$query = 'DELETE comic_chatacter_power WHERE character_id = ' . $character_id;
			mysqli_query($db, $query) or die (mysqli_error($db));

			$query = 'DELETE comic_rivalry WHERE hero_id = ' . $character_id . ' OR villain_id = ' . $character_id;
			mysqli_query($db, $query) or die (mysqli_error($db));

			$redirect = 'list_characters.php';
		break;

		case 'Edit Character':

			// escape incoming values to protect database
			$character_id = (int)$_POST['character_id'];
			$alias = mysqli_real_escape_string($_POST['alias']);
			$real_name = mysqli_real_escape_string($_POST['real_name']);
			$address = mysqli_real_escape_string($_POST['address']);
			$city = mysqli_real_escape_string($_POST['city']);
			$state = mysqli_real_escape_string($_POST['state']);
			$zipcode_id = mysqli_real_escape_string($_POST['zipcode_id']);
			$alignment = ($_POST['alignment'] == 'good') ? 'good' : 'evil';

			// update exixting character information in tables

			$query = 'INSERT IGNORE INTO comic_zipcode (zipcode_id, state, city) VALUES ("' . $zipcode_id . '", "' . $state . '", "' . $city . '")';
			mysqli_query($db, $query);

			$query = 'UPDATE comic_chatacter c, comic_lair l SET
			 c.alias = ' . $alias . ',
			 c.real_name =  ' . $real_name . ',
			 l.address = ' . $address . ',
			 l.zipcode_id = ' . $zipcode_id . ',
			 c.alignment = ' . $alignment . ' WHERE c.character_id = ' . $character_id . ' AND c.lair_id = l.lair_id';
			 mysqli_query($db, $query) or die (mysqli_error($db));

			 $query = 'DELETE comic_character_power WHERE character_id = ' . $character_id;
			 mysqli_query($db, $query) or die (mysqli_error($db));

			 if (!empty($_POST['powers'])) {
			 	$values[];
			 	foreach ($_POST['powers'] as $power_id) {
			 		$values[] = sprintf(('%d, %d'), $character_id, $power_id);
			 	}
			 	$query = 'INSERT IGNORE INTO comic_character_power (character_id, power_id) VALUES ' . implode(',', $values);
			 	mysqli_query($db, $query) or die (mysqli_error($db));
			 }

			 $query = 'DELETE from comic_rivalry WHERE hero_id = ' . $character_id . ' OR villain_id = ' . $character_id;
			 mysqli_query($db, $query) or die (mysqli_error($db));

			 if(!empty($_POST['rivalries'])){
			 	$values[];
			 	foreach ($_POST['rivalries'] as $rival_id) {
			 		$values[] = sprintf(('%d, %d'), $character_id, $rival_id);
			 	}
			 	$columns = ($alignment == 'good') ? '(hero_id, villain_id)' : '(villain_id, hero_id)';
			 	$query = 'INSERT IGNORE INTO comic_rivalry ' . columns . ' VALUES ' . implode(',', $values);
			 	mysqli_query($db, $query) or die (mysqli_error($db));
			 }

			$redirect = 'list_characters.php';
		break;

		case 'Delete Selected Powers':

			if(!empty($_POST['powers'])){
				$power = implode(',', $_POST['powers']);

				$query = 'DELETE comic_power WHERE power_id IN (' . $power . ')';
				mysqli_query($db, $power) or die (mysqli_error($db));

				$query = 'DELETE comic_character_power WHERE power_id IN (' . $power_id . ')';
				mysqli_query($db, $query) or die (mysqli_error($db));
			}

			$redirect = 'edit_power.php';
		break;

		case 'Add New Power':

			$power = trim($_POST['powers']);
			if($power != ''){
				$power = mysqli_real_escape_string($_POST['power']);

				$query = 'INSERT INTO comic_power (power_id, power) VALUES (NULL, "' . $power . '")';
				mysqli_query($db, $query) or die (mysqli_error($db)); 
			}
			
			$redirect = 'edit_power.php';
		break;

		default:
			$redirect = 'list_characters.php';
	}

	header ('Location: ' . $redirect);
 ?>